# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'My ACR Connection'
    repository: 'dotnet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
    addPipelineData: false
    addBaseImageData: false
  displayName: 'Bulding and Publishing Docker Image to ACR'

